version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.2.0

executors:
  base:
    docker:
      - image: cimg/node:18.12.1
        user: root

commands:
  install-node-packages:
    description: Install node packages
    steps:
      - restore_cache:
          key: node-cache-v2-{{ checksum "package-lock.json" }}
      - run:
          name: Install node packages
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: node-cache-v2-{{ checksum "package-lock.json" }}

jobs:
  tests:
    executor: base
    steps:
      - checkout
      - install-node-packages
      - run:
          name: Run linter and unit tests with coverage
          command: npm run quality
  check-for-pr:
    executor: base
    steps:
      - checkout
      - run: |
          if [[ $CIRCLE_PULL_REQUEST ]]; then
            circleci-agent step halt
          fi
      - continuation/continue:
          configuration_path: .circleci/deployment-workflow.yml
  docker-push:
    executor: base
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.12
          docker_layer_caching: true
      - run:
          name: Build and push Docker image to DockerHub
          command: ./docker_push.sh

workflows:
  main:
    jobs:
      - tests
      - check-for-pr:
          requires:
            - tests
      - approve-docker-push:
          type: approval
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - docker-push:
          requires:
            - approve-docker-push
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
